### ISSUE TITLE
上海部门数据处理系统相关问题-2017-06-26

### ISSUE THREAD

**Issue by luyiroger** [linlexing/tjmlk#2]
目前系统中存在的一些问题

1.	数据维护->部门数据->待处理单位维护，模板中通过在列表的方式进行单位筛选超过100条记录，筛选就会失败。
 

2.	数据维护->部门数据->待处理单位维护，打开一家变动类型1的单位，点击应用名录点击新增，会跳出名录库里的报表。但是如果此时中断操作，将这张报表关闭，待处理单位维护中这家单位的记录会消失，单位记录再次出现的时间不确定，可能几分钟，有可能要几天才会重新出现这条记录。能否改为，停止添加名录库表格后，这条记录直接回到待处理维护中。

3.	数据维护->部门数据->待处理单位维护，模板中显示的列需增加【营业收入】这一字段。

4.	数据维护->部门数据->待处理单位维护，划分处理地操作功能目前不太稳定，后台运作时间从几分钟到一两天不等，直接影响基层工作效率。另外有区级统计局反映部门数据处理系统划分处理地时，需要等一个上一个划分处理地的指令完全处理完后，才能继续操作下一个划分处理地的指令。如果上一个还没处理完，直接执行下一个划分处理地指令，少数待划分单位的处理地有可能出现划分错误的情况。

**Comment by linlexing** [comment]
1.超过100条记录，筛选失败的，请给出具体的指标名，内容，以及程序截图
2.由于其他省大批量更新或接入大量税务数据，引起合并缓慢，从而引起该问题，无解
3.该处模板中的指标均是参考，当有多个来源时，指标内容随机取，因此，营业收入这类数值指标，应当用关联查询语句查询。
4.后台合并时，会停止划分处理地，因此，但有几百万的数据在合并时，划分处理地等上几天很正常。

**Comment by luyiroger** [comment]
1. 数据维护->部门数据->待处理单位维护中，在显示的待处理单位中，挑选100条以上的记录（例如选择青浦准四上单位共158条记录 详见公用模板中 “青浦准四上”），点击查询，出现下图界面。
![111](https://user-images.githubusercontent.com/29699558/27527081-7970c1bc-5a7c-11e7-81e6-6348bc05e458.png)

2. 如该情况无法优化处理，基层利用本系统进行单位核查将非常困难

4. 如该情况无法优化处理，简单的划分处理地就需要很长时间，直接影响工作效率

**Comment by linlexing** [comment]
1.已经核实并改正，等待下一版程序更新
2.刚接入的省份首次处理数据时期，才会有此类问题，正常后就无碍

**Comment by linlexing** [comment]
版本已经更新
