### ISSUE TITLE
在名录库外部整理部门数据时，增加的备注内容，合并比对后，能不能在法人或产业待处理中的“备注”栏看见。

### ISSUE THREAD

**Issue by dashberlin** [linlexing/tjmlk#4]
在名录库外部整理部门数据时，增加的备注内容，合并比对后，能不能在法人或产业待处理中的“备注”栏看见。

**Comment by linlexing** [comment]
备注 只有 国税、地税有，工商、名录均无，所以待处理单位中也就没有该指标。待处理单位中，只存放通用的指标，不存放部门特殊指标。

**Comment by dashberlin** [comment]
在法人或产业待处理单位节点下，点击“打开部门表”，显示的是“修改部门比对结果”，此表中有个“备注”栏。       
      我们想把在外部整理各部门数据时写的备注内容全部或在”部门比对结果“表中的备注栏。这样方便基层知道这个单位在各部门的一些特殊处理以及普查中心人员在整理时做的一些特殊处理，这些处理内容都是有利名录维护的信息。（如：税务要求不能公布单个企业的具体营业收入、纳税金额信息，我们就处理成收入区间、纳税金额区间来下发）
      名录库“数据交换”节点下，导入各部门数据的接口中都有”备注“栏，我们的特殊处理信息就是放在这的。
       总之就是想把所有来源的备注内容体现在”部门比对结果“表中的”备注“栏中。

**Comment by dashberlin** [comment]
在法人或产业待处理单位节点下，点击“打开部门表”，显示的是“修改部门比对结果”，此表中有个“备注”栏。我们想把在外部整理各部门数据时写的备注内容全部或在”部门比对结果“表中的备注栏。这样方便基层知道这个单位在各部门的一些特殊处理以及普查中心人员在整理时做的一些特殊处理，这些处理内容都是有利名录维护的信息。（如：税务要求不能公布单个企业的具体营业收入、纳税金额信息，我们就处理成收入区间、纳税金额区间来下发）。名录库“数据交换”节点下，导入各部门数据的接口中都有”备注“栏，我们的特殊处理信息就是放在这的。总之就是想把所有来源的备注内容体现在”部门比对结果“表中的”备注“栏中。

**Comment by linlexing** [comment]
老系统？

**Comment by dashberlin** [comment]
是的。

**Comment by linlexing** [comment]
老系统我记得是有这个功能，去试下，记得备注里不要有空格
