### ISSUE TITLE
河北1

### ISSUE THREAD

**Issue by tjmlk13** [linlexing/tjmlk#8]
建议在点击“应用名录”按钮后出现的“应用到名录”对话框中，选择指标时可使用shift（上档键）来批量选择

**Comment by tjmlk13** [comment]
建议导航栏不要随滑条滚动而隐藏，方便选择菜单项；缩小或可调菜单栏宽度

**Comment by linlexing** [comment]
滚动隐藏是节省屏幕垂直空间，造成导航栏稍稍不便，两者孰优孰劣，不好说，先不改；菜单栏弹出显示，选择后自动隐藏，因此宽度调整没有意义；
